version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
    - 27017:27017
  app:
    image: cmduquer/restapi
    ports:
    - 8080:8080
    links:
    - mongodb